# Generated by Django 5.1.3 on 2024-12-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
